Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [14]:
import numpy as np

def AlexandreVandermonde(l, n,increasing = False):
    if increasing:
        print(np.array([ j** i for j in l for i in range(N)]).reshape(len(l), n))
    else:
        print(np.array([ j** (N-1-i) for j in l for i in range(N)]).reshape(len(l), n))
        
lst = [1,2,3,4,5]
n = 3
print('with decreasing boolean argument ')
print('\n')
AlexandreVandermonde(np.array(lst),n)
print('\n')
print('with increasing boolean argument ')
print('\n')
AlexandreVandermonde(np.array(lst),n, increasing= True)

with decreasing boolean argument 


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


with increasing boolean argument 


[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


Problem Statement 2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [15]:
var= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
window = 3
result = []

for i in range(len(var)):
    if i != len(var)-2:
        result.append((var[i]+var[i+1]+var[i+2])/window)
    else:
        break
result_size = len(var)-window+1
print(f'average sequence size: {result_size}')
print(f'result list size: {len(result)}')
for i in range(len(result)):
    print(f'y{i+1} = {result[i]}')

average sequence size: 11
result list size: 11
y1 = 5.0
y2 = 4.666666666666667
y3 = 5.666666666666667
y4 = 6.666666666666667
y5 = 9.666666666666666
y6 = 28.666666666666668
y7 = 49.333333333333336
y8 = 72.66666666666667
y9 = 84.0
y10 = 93.33333333333333
y11 = 116.33333333333333
